### ISSUE TITLE
Error on nas4free/freebsd

### ISSUE THREAD

**Issue by webserfer** [jesseward/plex-lastfm-scrobbler#26]
Traceback (most recent call last):
  File "/usr/local/bin/plex-scrobble.py", line 89, in <module>
    'mediaserver_log_location': platform_log_directory(),
  File "/usr/local/bin/plex-scrobble.py", line 29, in platform_log_directory
    return LOG_DEFAULTS[platform.system()]
KeyError: 'FreeBSD'

**Comment by jesseward** [comment]
fix applied in c4376a6 . thanks
