### ISSUE TITLE
Mock + Setuptools installation issues

### ISSUE THREAD

**Issue by jesseward** [jesseward/plex-lastfm-scrobbler#48]
Issues installing Mock seen in OSX and older versions of Ubuntu. Looks to be due to a bug in `setuptools`.
```
Copying pyparsing-2.1.10-py2.7.egg to /private/var/folders/b_/f18v0pvd6xq091flxcgl9fvm0000gn/T/easy_install-coTkZz/mock-2.0.0/.eggs

Installed /private/var/folders/b_/f18v0pvd6xq091flxcgl9fvm0000gn/T/easy_install-coTkZz/mock-2.0.0/.eggs/pyparsing-2.1.10-py2.7.egg
Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/private/var/folders/b_/f18v0pvd6xq091flxcgl9fvm0000gn/T/easy_install-coTkZz/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/private/var/folders/b_/f18v0pvd6xq091flxcgl9fvm0000gn/T/easy_install-coTkZz/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/private/var/folders/b_/f18v0pvd6xq091flxcgl9fvm0000gn/T/easy_install-coTkZz/mock-2.0.0/.eggs/pbr-1.10.0-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
  File "/Users/jesse/.virtualenvs/p2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1481, in evaluate_marker
    return cls.interpret(parser.expr(text).totuple(1)[1])
  File "/Users/jesse/.virtualenvs/p2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1515, in interpret
    return op(nodelist)
  File "/Users/jesse/.virtualenvs/p2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1429, in atom
    return cls.interpret(nodelist[2])
  File "/Users/jesse/.virtualenvs/p2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1515, in interpret
    return op(nodelist)
  File "/Users/jesse/.virtualenvs/p2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1450, in comparison
    raise SyntaxError(msg)
SyntaxError: '<' operator not allowed in environment markers
```

**Comment by jesseward** [comment]
seen here as well https://github.com/openaps/openaps/issues/95

**Comment by jesseward** [comment]
work around in https://github.com/jesseward/plex-lastfm-scrobbler/commit/3404178e3f4f2efb3f24f837060ad83e3773d08f
